version: '3.8'

services:
  h2-db:
    image: oscarfonts/h2
    container_name: watchott-db
    ports:
      - "8082:81"
      - "9092:9092"
    volumes:
      - h2-data:/opt/h2-data
    environment:
      - H2_OPTIONS=-tcpAllowOthers -tcpPort 9092 -ifNotExists
    restart: always

  redis:
    image: redis
    container_name: watchott-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always


  watchott-api:
    build:
      context: /watchott-api
      dockerfile: Dockerfile
    container_name: watchott-api-server
    ports:
      - "8080:8080"
    depends_on:
      - h2-db
    volumes:
      - ./watchott-api/build:/api/build
      - ./config:/api/config
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    restart: on-failure


  watchott-web:
    build:
      context: /watchott-web
      dockerfile: Dockerfile
    container_name: watchott-web-server
    ports:
      - "5173:5173"
    volumes:
      - ./watchott-web:/web
      - /web/node_modules
    depends_on:
      - watchott-api
    restart: on-failure

volumes:
  h2-data:
    driver: local
  redis-data:
    driver: local