server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://h2-db:9092/opt/h2-data/testdb
    username: sa
    password:

  redis:
    host: redis
    port: 6379

  cache:
    type: redis